// Code generated by errors generator. DO NOT EDIT.

package common

func init() {
	GoFiles = append(GoFiles, errors_amount)
}

var errors_amount = bytesReader{
	name: "errors_amount",
	data: []byte(`[
  {
    "Code": "ExceededQuota",
    "HTTPCode": 403,
    "Message": "The specified quota {{QuotaName}} is exceeded.",
    "Comment": "主要是创建类的接口用户级别的额度超过限制。"
  },
  {
    "Code": "ExceededLimit",
    "HTTPCode": 403,
    "Message": "The specified product limit {{LimitName}} is exceeded.",
    "Comment": "主要是创建类的接口产品形态级别的超越了限制，比如制定规格的VCI最多的CNI到达上限，挂载的存储设备超过了产品规定的上限。"
  },
  {
    "Code": "InsufficientBalance",
    "HTTPCode": 403,
    "Message": "Your account does not have enough balance.",
    "Comment": "账户余额不足（导致无法创建新资源或者完成变配）。"
  },
  {
    "Code": "AccountUnbalanced",
    "HTTPCode": 403,
    "Message": "Your account has ran out of balance.",
    "Comment": "账户欠费（导致无法创建新资源或者完成变配）。"
  },
  {
    "Code": "AccountCreditUnbalanced",
    "HTTPCode": 403,
    "Message": "Your account has ran out of credit.",
    "Comment": "账户信用额度不足（导致无法创建新资源或者完成变配）。"
  }
]`),
}
