{{- if .Values.server.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secret-keeper-server
  namespace: sailor-moon
  annotations:
    kubernetes.io/ingress.class: {{ .Values.server.ingress.class }}
spec:
  rules:
    - host: {{ .Values.server.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: secret-keeper-server
                port:
                  name: http
{{- end -}}
